# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: migration-discord-events
on:
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API migration discord events
        run: |
          curl --request POST \
          --url 'https://frontend.cafe/api/import-events'
